### ISSUE TITLE
Same mail repeatedly sent every hour

### ISSUE THREAD

**Issue by anssiko** [w3c/transition-issues-bot#1]
@plehegar, as of writing this, transition-issues-bot has sent 20 identical mails to the chairs list about [this transition](https://github.com/w3c/transitions/issues/411), see the list archive: https://lists.w3.org/Archives/Member/chairs/2022JanMar/

The mails are sent exactly one hour apart each. This looks like a configuration bug (typo in crontab?), but I thought I'll open this issue here for context.

**Comment by jnurthen** [comment]
And they are not threaded either so not so easy to ignore the thread in mail client.

**Comment by plehegar** [comment]
Fixed in https://github.com/w3c/transition-issues-bot/commit/235de6e2167c228f160171d67d78cf9d5583af23

**Comment by anssiko** [comment]
Thanks for fixing this!
